const WAYPOINT_FETCHED = 'waypoints.WAYPOINT_FETCHED';
const WAYPOINT_ADDED = 'waypoints.WAYPOINT_ADDED';
const WAYPOINT_DELETED = 'waypoints.WAYPOINT_DELETED';
const WAYPOINT_MOVED = 'waypoints.WAYPOINT_MOVED';
const WAYPOINT_COORDINATES_CHANGED = 'waypoints.WAYPOINT_COORDINATES_CHANGED';

export { WAYPOINT_FETCHED, WAYPOINT_ADDED, WAYPOINT_DELETED, WAYPOINT_MOVED, WAYPOINT_COORDINATES_CHANGED };
